
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import jssc.SerialPort;
import jssc.SerialPortException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lordsinsentido
 */
public class Principal extends javax.swing.JFrame {
    private ConexionBaseDeDatos conexionBaseDeDatos;
    private Connection conexion;
    private Usuario usuarioAutenticado;
    
    private SerialPort puerto;
    
    private boolean seInicioSesion = false;

    public Principal() {
        try {
            conexionBaseDeDatos = new ConexionBaseDeDatos();
            conexion = conexionBaseDeDatos.conexion();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        initComponents();
        
        traerDatos();
        
        //desactivarPestannas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoActualizarUsuario = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        actualizarUsuarioEntradaNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        actualizarUsuarioEntradaApellido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        actualizarUsuarioEntradaUsuario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        actualizarUsuarioEntradaContrasenna = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        actualizarUsuarioOpcionesRol = new javax.swing.JComboBox<>();
        actualizarUsuarioBotonActualizarUsuario = new javax.swing.JButton();
        actualizarUsuarioTextoAlerta = new javax.swing.JLabel();
        actualizarUsuarioBotonCancelar = new javax.swing.JButton();
        actualizarIdUsuario = new javax.swing.JLabel();
        dialogoCrearUsuario = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioEntradaNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usuarioEntradaApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usuarioEntradaUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usuarioEntradaContrasenna = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        usuarioOpcionesRol = new javax.swing.JComboBox<>();
        usuarioBotonCrearUsuario = new javax.swing.JButton();
        usuarioTextoAlerta = new javax.swing.JLabel();
        pestannasMenu = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loginEntradaUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        loginEntradaContrasenna = new javax.swing.JPasswordField();
        loginBotonIniciarSesión = new javax.swing.JButton();
        loginBotonCerrarSesion = new javax.swing.JButton();
        loginTextoAlerta = new javax.swing.JLabel();
        panelControl = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        controlBotonEncender = new javax.swing.JButton();
        controlBotonApagar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        controlSliderVelocidad = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelAdmon = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        admonTablaUsuarios = new javax.swing.JTable();
        admonBotonCrearUsuario = new javax.swing.JButton();

        dialogoActualizarUsuario.setTitle("Actualizar registro");
        dialogoActualizarUsuario.setBounds(new java.awt.Rectangle(20, 20, 350, 350));
        dialogoActualizarUsuario.setLocation(new java.awt.Point(50, 50));
        dialogoActualizarUsuario.setModal(true);

        jLabel18.setText("Actualizar usuario");

        jLabel19.setText("Nombre");

        actualizarUsuarioEntradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarUsuarioEntradaNombreActionPerformed(evt);
            }
        });

        jLabel20.setText("Apellido");

        actualizarUsuarioEntradaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarUsuarioEntradaApellidoActionPerformed(evt);
            }
        });

        jLabel21.setText("Nombre de usuario");

        jLabel22.setText("Contraseña");

        jLabel23.setText("Rol");

        actualizarUsuarioOpcionesRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operador", "Administrador" }));
        actualizarUsuarioOpcionesRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarUsuarioOpcionesRolActionPerformed(evt);
            }
        });

        actualizarUsuarioBotonActualizarUsuario.setText("Actualizar usuario");
        actualizarUsuarioBotonActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarUsuarioBotonActualizarUsuarioActionPerformed(evt);
            }
        });

        actualizarUsuarioBotonCancelar.setText("Cancelar");
        actualizarUsuarioBotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarUsuarioBotonCancelarActionPerformed(evt);
            }
        });

        actualizarIdUsuario.setEnabled(false);

        javax.swing.GroupLayout dialogoActualizarUsuarioLayout = new javax.swing.GroupLayout(dialogoActualizarUsuario.getContentPane());
        dialogoActualizarUsuario.getContentPane().setLayout(dialogoActualizarUsuarioLayout);
        dialogoActualizarUsuarioLayout.setHorizontalGroup(
            dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarUsuarioEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarUsuarioEntradaContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarUsuarioEntradaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarIdUsuario))
                    .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarUsuarioEntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarUsuarioOpcionesRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                        .addComponent(actualizarUsuarioBotonActualizarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(actualizarUsuarioBotonCancelar))
                    .addComponent(actualizarUsuarioTextoAlerta))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        dialogoActualizarUsuarioLayout.setVerticalGroup(
            dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoActualizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(actualizarIdUsuario))
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(actualizarUsuarioEntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(actualizarUsuarioEntradaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(actualizarUsuarioEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(actualizarUsuarioEntradaContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(actualizarUsuarioOpcionesRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarUsuarioBotonActualizarUsuario)
                    .addComponent(actualizarUsuarioBotonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualizarUsuarioTextoAlerta)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        dialogoCrearUsuario.setAlwaysOnTop(true);
        dialogoCrearUsuario.setBounds(new java.awt.Rectangle(20, 20, 350, 350));
        dialogoCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dialogoCrearUsuario.setFocusTraversalPolicyProvider(true);
        dialogoCrearUsuario.setLocation(new java.awt.Point(50, 50));
        dialogoCrearUsuario.setModal(true);

        jLabel1.setText("Crear usuario nuevo");

        jLabel2.setText("Nombre");

        usuarioEntradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEntradaNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        usuarioEntradaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEntradaApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre de usuario");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Rol");

        usuarioOpcionesRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operador", "Administrador" }));
        usuarioOpcionesRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioOpcionesRolActionPerformed(evt);
            }
        });

        usuarioBotonCrearUsuario.setText("Crear usuario");
        usuarioBotonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBotonCrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoCrearUsuarioLayout = new javax.swing.GroupLayout(dialogoCrearUsuario.getContentPane());
        dialogoCrearUsuario.getContentPane().setLayout(dialogoCrearUsuarioLayout);
        dialogoCrearUsuarioLayout.setHorizontalGroup(
            dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioTextoAlerta)
                    .addGroup(dialogoCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioEntradaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(dialogoCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioEntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioEntradaContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioOpcionesRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usuarioBotonCrearUsuario))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        dialogoCrearUsuarioLayout.setVerticalGroup(
            dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usuarioEntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usuarioEntradaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usuarioEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usuarioEntradaContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usuarioOpcionesRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(usuarioBotonCrearUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioTextoAlerta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de banda de producción");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(20, 20, 500, 400));
        setLocation(new java.awt.Point(50, 50));

        panelLogin.setEnabled(false);

        jLabel7.setText("Inicio de sesión");

        jLabel8.setText("Nombre de usuario");

        jLabel9.setText("Contraseña");

        loginBotonIniciarSesión.setText("Iniciar sesión");
        loginBotonIniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBotonIniciarSesiónActionPerformed(evt);
            }
        });

        loginBotonCerrarSesion.setText("Cerrar sesión");
        loginBotonCerrarSesion.setEnabled(false);
        loginBotonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBotonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginEntradaContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(loginBotonIniciarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginBotonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginTextoAlerta))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(loginEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(loginEntradaContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBotonIniciarSesión)
                    .addComponent(loginBotonCerrarSesion))
                .addGap(18, 18, 18)
                .addComponent(loginTextoAlerta)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        pestannasMenu.addTab("Inciar sesión", panelLogin);

        panelControl.setEnabled(false);

        jLabel10.setText("Control de la banda de producción");

        jLabel11.setText("Seleccionar estado");

        controlBotonEncender.setText("Encender");
        controlBotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlBotonEncenderActionPerformed(evt);
            }
        });

        controlBotonApagar.setText("Apagar");

        jLabel12.setText("Dirección de la banda");

        jButton3.setText("Adelante");

        jButton4.setText("Atrás");

        jButton5.setText("Manual");

        jLabel13.setText("Velocidad");

        jLabel14.setText("Más lento");

        jLabel15.setText("Más rápido");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(controlBotonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(controlBotonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addComponent(controlSliderVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlBotonEncender)
                    .addComponent(controlBotonApagar))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlSliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pestannasMenu.addTab("Control de la banda", panelControl);

        jLabel16.setText("Administración de usuario registrados");

        admonTablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Nombre", "Apellidos", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        admonTablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admonTablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(admonTablaUsuarios);

        admonBotonCrearUsuario.setText("Agregar usuario");
        admonBotonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admonBotonCrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdmonLayout = new javax.swing.GroupLayout(panelAdmon);
        panelAdmon.setLayout(panelAdmonLayout);
        panelAdmonLayout.setHorizontalGroup(
            panelAdmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdmonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdmonLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdmonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(admonBotonCrearUsuario)))
                .addContainerGap())
        );
        panelAdmonLayout.setVerticalGroup(
            panelAdmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdmonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admonBotonCrearUsuario)
                .addContainerGap())
        );

        pestannasMenu.addTab("Administrar usuarios", panelAdmon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestannasMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestannasMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBotonIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBotonIniciarSesiónActionPerformed
        try {   // Se manda la petición a la base de datos
            Statement iniciarSesion = conexion.createStatement();   // Se crea el statement encargado de realizar la conexión y acción a la base de datos
            ResultSet resultado = iniciarSesion.executeQuery("SELECT id, usuario, contrasenna, nombre, apellidos, rol FROM usuarios WHERE usuario = '" + loginEntradaUsuario.getText().trim() + "';");   // Se le asigna el comando a ejecutar, y posterior a ello, se guardan los resultados
            
            while(resultado.next()) {  // Aquí se busca entre los resultados al usuario que trata de iniciar sesión
                if(resultado.getString(2).equals(loginEntradaUsuario.getText().trim()) && resultado.getString(3).equals(loginEntradaContrasenna.getText().trim())) {   // Se busca que el resultado que se encontró contenga el mismo usuario y la misma contraseña, si fue encontrado, ejecutará las siguientes líneas de código
                    seInicioSesion = true;   // Se establece que se ha iniciado sesión
                    usuarioAutenticado = new Usuario(resultado.getInt(1), resultado.getString(2), resultado.getString(4), resultado.getString(5), resultado.getInt(6));
                    
                    switch(usuarioAutenticado.getRol()) {
                        case 0 :
                            pestannasMenu.setEnabledAt(1, true);
                            break;
                        case 1 :
                            pestannasMenu.setEnabledAt(1, true);
                            pestannasMenu.setEnabledAt(2, true);
                            break;
                    }
                    
                    loginEntradaUsuario.setEditable(false);
                    loginEntradaContrasenna.setText("Protegemos tu contrasenna quitándola");
                    loginEntradaContrasenna.setEditable(false);
                    loginBotonIniciarSesión.setEnabled(false);
                    loginBotonCerrarSesion.setEnabled(true);
                    
                    loginTextoAlerta.setText("Bienvenido " + usuarioAutenticado.getNombre() + " " + usuarioAutenticado.getApellido());
                    
                }else{   // Si no fue encontrado, se ejecutarán las siguientes líneas de código
                    loginTextoAlerta.setText("No se ha encontrado el usuario, revisa tus credenciales y vuelve a intentarlo");
                }
            }
            
        } catch (Exception e) {
            usuarioTextoAlerta.setText("No se pudo conectar con la base de datos");
        }
    }//GEN-LAST:event_loginBotonIniciarSesiónActionPerformed

    private void loginBotonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBotonCerrarSesionActionPerformed
        desactivarPestannas();
        
        usuarioAutenticado = null;
        
        loginEntradaUsuario.setEditable(true);
        loginEntradaContrasenna.setEditable(true);
        loginEntradaContrasenna.setText("");
        loginBotonIniciarSesión.setEnabled(true);
        loginBotonCerrarSesion.setEnabled(false);
        
        loginTextoAlerta.setText("Se ha cerrado tu sesión");
    }//GEN-LAST:event_loginBotonCerrarSesionActionPerformed

    private void controlBotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlBotonEncenderActionPerformed
        try {   // Se intenta realizar la conexión con el puerto serial, si se logra conectar ejecutará el siguiente código
            puerto = new SerialPort("/dev/ttyACM0");   // Se especifica el puerto al que se trata de conectar
            puerto.openPort();   // Se inicializa el puerto
            puerto.setParams(SerialPort.BAUDRATE_19200, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);   // Se establecen los parámetros que tendrá la conexión
        } catch (SerialPortException ex) {   // En caso de que no se haya podido conectar, ejecutará el siguiente código
        }
    }//GEN-LAST:event_controlBotonEncenderActionPerformed

    private void admonTablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admonTablaUsuariosMouseClicked
        String idDelUsuario = (String) admonTablaUsuarios.getValueAt(admonTablaUsuarios.getSelectedRow(), 0);
        
        try {
            Statement traerUsuario = conexion.createStatement();   // Se crea el statement encargado de realizar la conexión y acción a la base de datos
            ResultSet resultado = traerUsuario.executeQuery("SELECT id, usuario, contrasenna, nombre, apellidos, rol FROM usuarios WHERE id = " + idDelUsuario + ";");   // Se le asigna el comando a ejecutar, y posterior a ello, se guardan los resultados
            
            actualizarIdUsuario.setText(resultado.getString(1));
            actualizarUsuarioEntradaUsuario.setText(resultado.getString(2));
            actualizarUsuarioEntradaContrasenna.setText(resultado.getString(3));
            actualizarUsuarioEntradaNombre.setText(resultado.getString(4));
            actualizarUsuarioEntradaApellido.setText(resultado.getString(5));
            actualizarUsuarioOpcionesRol.setSelectedIndex(resultado.getInt(6));
            
            //System.out.println(actualizarIdUsuario.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        dialogoActualizarUsuario.setVisible(true);
    }//GEN-LAST:event_admonTablaUsuariosMouseClicked

    private void usuarioBotonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBotonCrearUsuarioActionPerformed
        try {
            PreparedStatement agregarUsuario = conexion.prepareStatement("INSERT INTO usuarios VALUES(?,?,?,?,?,?);"); // Se crea el statement encargado de conectar con la base de datos y realizar la acción en ella

            if(!usuarioEntradaUsuario.getText().isEmpty() && !usuarioEntradaContrasenna.getText().isEmpty() && !usuarioEntradaNombre.getText().isEmpty() && !usuarioEntradaApellido.getText().isEmpty()){
                agregarUsuario.setString(2, usuarioEntradaUsuario.getText().trim());
                agregarUsuario.setString(3, usuarioEntradaContrasenna.getText().trim());
                agregarUsuario.setString(4, usuarioEntradaNombre.getText().trim());
                agregarUsuario.setString(5, usuarioEntradaApellido.getText().trim());
                agregarUsuario.setInt(6, usuarioOpcionesRol.getSelectedIndex());

                agregarUsuario.executeUpdate();

                usuarioEntradaUsuario.setText("");
                usuarioEntradaContrasenna.setText("");
                usuarioEntradaNombre.setText("");
                usuarioEntradaApellido.setText("");
                usuarioOpcionesRol.setSelectedIndex(0);
                
                traerDatos();

                dialogoCrearUsuario.setVisible(false);
                usuarioTextoAlerta.setText("");
            }else{
                usuarioTextoAlerta.setText("Faltan campos");
            }

        } catch (Exception e) {
            usuarioTextoAlerta.setText("No se pudo conectar con la base de datos");
        }
    }//GEN-LAST:event_usuarioBotonCrearUsuarioActionPerformed

    private void usuarioOpcionesRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioOpcionesRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioOpcionesRolActionPerformed

    private void usuarioEntradaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEntradaApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioEntradaApellidoActionPerformed

    private void usuarioEntradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEntradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioEntradaNombreActionPerformed

    private void admonBotonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admonBotonCrearUsuarioActionPerformed
        dialogoCrearUsuario.setVisible(true);
    }//GEN-LAST:event_admonBotonCrearUsuarioActionPerformed

    private void actualizarUsuarioEntradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuarioEntradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarUsuarioEntradaNombreActionPerformed

    private void actualizarUsuarioEntradaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuarioEntradaApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarUsuarioEntradaApellidoActionPerformed

    private void actualizarUsuarioOpcionesRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuarioOpcionesRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarUsuarioOpcionesRolActionPerformed

    private void actualizarUsuarioBotonActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuarioBotonActualizarUsuarioActionPerformed
        try {
            PreparedStatement actualizarUsuario = conexion.prepareStatement("UPDATE usuarios SET usuario = ?, contrasenna = ?, nombre = ?, apellidos = ?, rol = ? WHERE id = " + actualizarIdUsuario.getText() + ";"); // Se crea el statement encargado de conectar con la base de datos y realizar la acción en ella

            if(!actualizarUsuarioEntradaUsuario.getText().isEmpty() && !actualizarUsuarioEntradaContrasenna.getText().isEmpty() && !actualizarUsuarioEntradaNombre.getText().isEmpty() && !actualizarUsuarioEntradaApellido.getText().isEmpty()){
                actualizarUsuario.setString(1, actualizarUsuarioEntradaUsuario.getText().trim());
                actualizarUsuario.setString(2, actualizarUsuarioEntradaContrasenna.getText().trim());
                actualizarUsuario.setString(3, actualizarUsuarioEntradaNombre.getText().trim());
                actualizarUsuario.setString(4, actualizarUsuarioEntradaApellido.getText().trim());
                actualizarUsuario.setInt(5, actualizarUsuarioOpcionesRol.getSelectedIndex());

                actualizarUsuario.executeUpdate();

                actualizarUsuarioEntradaUsuario.setText("");
                actualizarUsuarioEntradaContrasenna.setText("");
                actualizarUsuarioEntradaNombre.setText("");
                actualizarUsuarioEntradaApellido.setText("");
                actualizarUsuarioOpcionesRol.setSelectedIndex(0);
                
                traerDatos();

                dialogoActualizarUsuario.setVisible(false);
                actualizarUsuarioTextoAlerta.setText("");
            }else{
                actualizarUsuarioTextoAlerta.setText("Faltan campos");
            }

        } catch (Exception e) {
            actualizarUsuarioTextoAlerta.setText("No se pudo conectar con la base de datos");
        }
    }//GEN-LAST:event_actualizarUsuarioBotonActualizarUsuarioActionPerformed

    private void actualizarUsuarioBotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuarioBotonCancelarActionPerformed
        dialogoActualizarUsuario.setVisible(false);
    }//GEN-LAST:event_actualizarUsuarioBotonCancelarActionPerformed

    private void desactivarPestannas() {   // Función que deshabilita las pestañas del programa para que el usuario no pueda acceder a ellas
        for(int i = 1; i < 3; i++) {
            pestannasMenu.setEnabledAt(i, false);
        }
    }
    
    private void traerDatos() {
        DefaultTableModel tablaUsuarios = (DefaultTableModel) admonTablaUsuarios.getModel();
        String [] datos = new String[5];
        
        try {
            Statement traerUsuarios = conexion.createStatement();   // Se crea el statement encargado de realizar la conexión y acción a la base de datos
            ResultSet resultado = traerUsuarios.executeQuery("SELECT id, usuario, nombre, apellidos, rol FROM usuarios;");   // Se le asigna el comando a ejecutar, y posterior a ello, se guardan los resultados
            
            while(resultado.next()) {
                for(int i = 0; i < 4; i++) {
                    datos[i] = resultado.getString(i + 1);
                }
                
                switch(resultado.getInt(5)) {
                    case 0:
                        datos[4] = "Operador";
                        break;
                        
                    case 1:
                        datos[4] = "Administrador";
                        break;
                }
                
                tablaUsuarios.addRow(datos);
            }
            
            admonTablaUsuarios.setModel(tablaUsuarios);
        } catch (Exception e) {
        }
            
    }
    

    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualizarIdUsuario;
    private javax.swing.JButton actualizarUsuarioBotonActualizarUsuario;
    private javax.swing.JButton actualizarUsuarioBotonCancelar;
    private javax.swing.JTextField actualizarUsuarioEntradaApellido;
    private javax.swing.JPasswordField actualizarUsuarioEntradaContrasenna;
    private javax.swing.JTextField actualizarUsuarioEntradaNombre;
    private javax.swing.JTextField actualizarUsuarioEntradaUsuario;
    private javax.swing.JComboBox<String> actualizarUsuarioOpcionesRol;
    private javax.swing.JLabel actualizarUsuarioTextoAlerta;
    private javax.swing.JButton admonBotonCrearUsuario;
    private javax.swing.JTable admonTablaUsuarios;
    private javax.swing.JButton controlBotonApagar;
    private javax.swing.JButton controlBotonEncender;
    private javax.swing.JSlider controlSliderVelocidad;
    private javax.swing.JDialog dialogoActualizarUsuario;
    private javax.swing.JDialog dialogoCrearUsuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginBotonCerrarSesion;
    private javax.swing.JButton loginBotonIniciarSesión;
    private javax.swing.JPasswordField loginEntradaContrasenna;
    private javax.swing.JTextField loginEntradaUsuario;
    private javax.swing.JLabel loginTextoAlerta;
    private javax.swing.JPanel panelAdmon;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTabbedPane pestannasMenu;
    private javax.swing.JButton usuarioBotonCrearUsuario;
    private javax.swing.JTextField usuarioEntradaApellido;
    private javax.swing.JPasswordField usuarioEntradaContrasenna;
    private javax.swing.JTextField usuarioEntradaNombre;
    private javax.swing.JTextField usuarioEntradaUsuario;
    private javax.swing.JComboBox<String> usuarioOpcionesRol;
    private javax.swing.JLabel usuarioTextoAlerta;
    // End of variables declaration//GEN-END:variables
}
